### ISSUE TITLE
Julia code has a type instability

### ISSUE THREAD

**Issue by aaowens** [davidzarruk/Parallel_Computing#1]
Cool paper! I found one performance issue with the Julia code.

The variable `VV` in the function `value` is not type stable. It is `Union{Int, Float64}`. This is because it is initialized as `-10 ^3`, which is an Int, but then becomes a Float when assigned to utility. 

I fixed this by changing line 130 to 
```
VV      = -10. ^3;
```
and line 148 to 
```
utility = -10. ^(5);
```
On my computer using 1 core, this sped it up from 25s to 15s.

**Comment by davidzarruk** [comment]
Thanks, I just updated the repository!
